// Generated by https://quicktype.io ctrl + shift + p -> paste JSON as code

export interface PokeResponse {
  count:    number;
  next:     string;
  previous: null;
  results:  Result[];
}

export interface Result {
  name: string;
  url:  string;
}
